{"uuid": "27d9848c-9940-47e5-96f8-a1c0ee9da304", "children": ["696f19af-cd2b-4582-8964-25d30857e51f"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: no such execution context\n  (Session info: chrome=125.0.6422.76)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D2141F52+60322]\n\t(No symbol) [0x00007FF6D20BCEC9]\n\t(No symbol) [0x00007FF6D1F77CE9]\n\t(No symbol) [0x00007FF6D1F5FCCE]\n\t(No symbol) [0x00007FF6D1F5E1E5]\n\t(No symbol) [0x00007FF6D1F5EBAF]\n\t(No symbol) [0x00007FF6D1F6E220]\n\t(No symbol) [0x00007FF6D1F85C6F]\n\t(No symbol) [0x00007FF6D1F8B67A]\n\t(No symbol) [0x00007FF6D1F5F33A]\n\t(No symbol) [0x00007FF6D1F8584F]\n\t(No symbol) [0x00007FF6D200BB5B]\n\t(No symbol) [0x00007FF6D1FEBFC3]\n\t(No symbol) [0x00007FF6D1FB9617]\n\t(No symbol) [0x00007FF6D1FBA211]\n\tGetHandleVerifier [0x00007FF6D245949D+3301613]\n\tGetHandleVerifier [0x00007FF6D24A36C3+3605267]\n\tGetHandleVerifier [0x00007FF6D2499440+3563664]\n\tGetHandleVerifier [0x00007FF6D21F4326+790390]\n\t(No symbol) [0x00007FF6D20C750F]\n\t(No symbol) [0x00007FF6D20C3404]\n\t(No symbol) [0x00007FF6D20C3592]\n\t(No symbol) [0x00007FF6D20B2F9F]\n\tBaseThreadInitThunk [0x00007FFA56C5257D+29]\n\tRtlUserThreadStart [0x00007FFA5736AA48+40]\n\n", "trace": "  File \"C:\\Users\\User\\PycharmProjects\\pythonProjectseleniumframework\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\User\\PycharmProjects\\pythonProjectseleniumframework\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\User\\PycharmProjects\\pythonProjectseleniumframework\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\PycharmProjects\\pythonProjectseleniumframework\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\PycharmProjects\\pythonProjectseleniumframework\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\PycharmProjects\\pythonProjectseleniumframework\\tests\\conftest.py\", line 18, in setup\n    driver.maximize_window()\n  File \"C:\\Users\\User\\PycharmProjects\\pythonProjectseleniumframework\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 499, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\User\\PycharmProjects\\pythonProjectseleniumframework\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\User\\PycharmProjects\\pythonProjectseleniumframework\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1716374984344, "stop": 1716374986629}], "start": 1716374984344, "stop": 1716374986916}